-- MySQL Script generated by MySQL Workbench
-- Thu Jun  7 13:08:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ExpressFood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ExpressFood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ExpressFood` DEFAULT CHARACTER SET utf8 ;
USE `ExpressFood` ;

-- -----------------------------------------------------
-- Table `ExpressFood`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`utilisateur` (
  `idUtilisateur` INT(100) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `motDePasse` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ExpressFood`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`client` (
  `idClient` INT(100) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  `numtelephone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `utilisateur_idUtilisateur` INT(100) NOT NULL,
  PRIMARY KEY (`idClient`, `utilisateur_idUtilisateur`),
  INDEX `fk_client_utilisateur1_idx` (`utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_client_utilisateur1`
    FOREIGN KEY (`utilisateur_idUtilisateur`)
    REFERENCES `ExpressFood`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ExpressFood`.`adresse_livraison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`adresse_livraison` (
  `idAdresse` INT(100) NOT NULL AUTO_INCREMENT,
  `rue` VARCHAR(255) NOT NULL,
  `numRue` INT(11) NULL DEFAULT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `codePostal` VARCHAR(5) NOT NULL,
  `otherInformation` VARCHAR(255) NULL DEFAULT NULL,
  `zoneAdresse` VARCHAR(45) NOT NULL,
  `client_idClient` INT(100) NOT NULL,
  PRIMARY KEY (`idAdresse`, `client_idClient`),
  INDEX `fk_adresse_livraison_client1_idx` (`client_idClient` ASC),
  CONSTRAINT `fk_adresse_livraison_client1`
    FOREIGN KEY (`client_idClient`)
    REFERENCES `ExpressFood`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ExpressFood`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`article` (
  `idArticle` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `auMenu` TINYINT(4) NOT NULL,
  `prixUnitaire` DECIMAL(5,2) NOT NULL,
  `stock` INT(100) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArticle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ExpressFood`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`commande` (
  `idCommande` INT(100) NOT NULL AUTO_INCREMENT,
  `dateCommande` DATETIME NOT NULL,
  `reglementClient` TINYINT(4) NOT NULL,
  `priseEnCharge` TINYINT(4) NOT NULL,
  `commandeLivree` TINYINT(4) NOT NULL,
  `prixTotal` DECIMAL(5,2) NOT NULL,
  `client_idClient` INT(100) NOT NULL,
  `client_utilisateur_idUtilisateur` INT(100) NOT NULL,
  PRIMARY KEY (`idCommande`, `client_idClient`, `client_utilisateur_idUtilisateur`),
  INDEX `fk_commande_client1_idx` (`client_idClient` ASC, `client_utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_commande_client1`
    FOREIGN KEY (`client_idClient` , `client_utilisateur_idUtilisateur`)
    REFERENCES `ExpressFood`.`client` (`idClient` , `utilisateur_idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ExpressFood`.`detail_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`detail_commande` (
  `commande_idCommande` INT(100) NOT NULL,
  `commande_client_idClient` INT(100) NOT NULL,
  `article_idArticle` VARCHAR(255) NOT NULL,
  `quantite` INT(100) NOT NULL,
  PRIMARY KEY (`commande_idCommande`, `commande_client_idClient`, `article_idArticle`),
  INDEX `fk_detail_commande_article1_idx` (`article_idArticle` ASC),
  CONSTRAINT `fk_detail_commande_commande1`
    FOREIGN KEY (`commande_idCommande` , `commande_client_idClient`)
    REFERENCES `ExpressFood`.`commande` (`idCommande` , `client_idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detail_commande_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `ExpressFood`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ExpressFood`.`livreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`livreur` (
  `idLivreur` INT(100) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `dispo` TINYINT(4) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `utilisateur_idUtilisateur` INT(100) NOT NULL,
  PRIMARY KEY (`idLivreur`, `utilisateur_idUtilisateur`),
  INDEX `fk_livreur_utilisateur1_idx` (`utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_livreur_utilisateur1`
    FOREIGN KEY (`utilisateur_idUtilisateur`)
    REFERENCES `ExpressFood`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ExpressFood`.`livraison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`livraison` (
  `commande_idCommande` INT(100) NOT NULL,
  `commande_client_idClient` INT(100) NOT NULL,
  `livreur_idLivreur` INT(100) NOT NULL,
  `tempsLivraisonEstime` INT(100) NOT NULL,
  PRIMARY KEY (`commande_idCommande`, `commande_client_idClient`, `livreur_idLivreur`),
  INDEX `fk_livraison_commande1_idx` (`commande_idCommande` ASC, `commande_client_idClient` ASC),
  CONSTRAINT `fk_livraison_livreur1`
    FOREIGN KEY (`livreur_idLivreur`)
    REFERENCES `ExpressFood`.`livreur` (`idLivreur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livraison_commande1`
    FOREIGN KEY (`commande_idCommande` , `commande_client_idClient`)
    REFERENCES `ExpressFood`.`commande` (`idCommande` , `client_idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ExpressFood`.`sac_livreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`sac_livreur` (
  `livreur_idLivreur` INT(100) NOT NULL,
  `article_idArticle` VARCHAR(255) NOT NULL,
  `stockLivreur` INT(100) NULL DEFAULT NULL,
  PRIMARY KEY (`livreur_idLivreur`, `article_idArticle`),
  INDEX `fk_stock_livreur_livreur1_idx` (`livreur_idLivreur` ASC),
  CONSTRAINT `fk_stock_livreur_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `ExpressFood`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_livreur_livreur1`
    FOREIGN KEY (`livreur_idLivreur`)
    REFERENCES `ExpressFood`.`livreur` (`idLivreur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
